namespace Microsoft.WindowsPhone.ImageUpdate.Tools.Common
{
	public enum ATTACH_VIRTUAL_DISK_FLAG
	{
		ATTACH_VIRTUAL_DISK_FLAG_NONE = 0,
		ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY = 1,
		ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER = 2,
		ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME = 4,
		ATTACH_VIRTUAL_DISK_FLAG_NO_LOCAL_HOST = 8
	}
}
