using System;

namespace Microsoft.WindowsPhone.ImageUpdate.Tools.Common
{
	[CLSCompliant(false)]
	public enum SecurityInformationFlags : uint
	{
		OWNER_SECURITY_INFORMATION = 1u,
		GROUP_SECURITY_INFORMATION = 2u,
		DACL_SECURITY_INFORMATION = 4u,
		SACL_SECURITY_INFORMATION = 8u,
		MANDATORY_ACCESS_LABEL = 16u,
		PROTECTED_DACL_SECURITY_INFORMATION = 2147483648u,
		PROTECTED_SACL_SECURITY_INFORMATION = 1073741824u,
		UNPROTECTED_DACL_SECURITY_INFORMATION = 536870912u,
		UNPROTECTED_SACL_SECURITY_INFORMATION = 268435456u
	}
}
