namespace Microsoft.WindowsPhone.ImageUpdate.InboxAppLib
{
	public enum APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE
	{
		APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE_APPLICATION,
		APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE_RESOURCE
	}
}
