namespace Microsoft.WindowsPhone.ImageUpdate.InboxAppLib
{
	public enum APPX_PACKAGE_ARCHITECTURE
	{
		APPX_PACKAGE_ARCHITECTURE_X86 = 0,
		APPX_PACKAGE_ARCHITECTURE_ARM = 5,
		APPX_PACKAGE_ARCHITECTURE_X64 = 9,
		APPX_PACKAGE_ARCHITECTURE_NEUTRAL = 11,
		APPX_PACKAGE_ARCHITECTURE_ARM64 = 12
	}
}
